### ISSUE TITLE
Cannot find AndroidManifest.xml

### ISSUE THREAD

**Issue by jtyrrell** [SamVerschueren/gulp-cordova-build-android#30]
Hi, I'm trying to build my Angular7 app using gulp-cordova-build-android.
But when executing this task:
gulp.task('androiddebug', ['clean','build'], () => {
  return gulp.src('dist')
    .pipe(create())
    .pipe(android())
    .pipe(gulp.dest('dist/android'));
});

I get the error:
{ Error: ENOENT: no such file or directory, open '[ProjectDir]\.cordova\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at GradleBuilder.extractRealProjectNameFromManifest ([ProjectDir]\.cordova\platforms\android\cordova\lib\builders\GradleBuilder.js:110:27)
    at GradleBuilder.prepBuildFiles ([ProjectDir]\.cordova\pl
atforms\android\cordova\lib\builders\GradleBuilder.js:149:21)
    at [ProjectDir]\.cordova\platforms\android\cordova\lib\bu
ilders\GradleBuilder.js:229:21
    at _fulfilled ([ProjectDir]\.cordova\platforms\android\co
rdova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done ([ProjectDir]\.cordova\platf
orms\android\cordova\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch ([ProjectDir]\.cordova
\platforms\android\cordova\node_modules\q\q.js:796:13)
    at [ProjectDir]\.cordova\platforms\android\cordova\node_m
odules\q\q.js:604:44
    at runSingle ([ProjectDir]\.cordova\platforms\android\cor
dova\node_modules\q\q.js:137:13)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '[ProjectDir]\\.cordova\\platforms\\android\\A
ndroidManifest.xml' }
(node:19812) UnhandledPromiseRejectionWarning
(node:19812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:19812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ZaLiTHkA** [comment]
I only just discovered this module earlier today, ran into this same problem. I suspect it's related to the fact that the structure of the `platforms` folder changed with `cordova-android@7.0.0`, [see this blog post](https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html) for more info.

going to fork this project now and see if I can get a local copy working for `cordova-android@^7` now.

**Comment by ZaLiTHkA** [comment]
actually, it seems this can't be controlled from `gulp-cordova-build-android`, the `AndroidManifest.xml` file path is being generated inside my project's `platforms/android/cordova/lib/builders/GradleBuilder.js@109`.

I don't see anything useful in [`cordova-lib`'s release notes](https://github.com/apache/cordova-lib/blob/master/RELEASENOTES.md) though.. I'm no expert with Cordova though, so it's possible that I'm just looking in the wrong place.

@SamVerschueren, any idea what needs to change for this one?

**Comment by ronnyroeller** [comment]
As a workaround you can define the location of the Manifest in the `config.xml` itself:
```xml
<resource-file src="platforms/android/app/src/main/AndroidManifest.xml" target="AndroidManifest.xml" />
```
